edx-solutions/api-integration

edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/groups/tests.py
edx_solutions_api_integration/groups/views.py
edx_solutions_api_integration/urls.py
edx_solutions_api_integration/users/serializers.py
edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py
setup.py

This PR has changes required in api_integration app related to renaming of `organizations` app.
@msaqib52 would you please review?

ziafazal/YONK-345:renaming organizations app

---

edx_solutions_api_integration/management/commands/migrate_orgdata.py
edx_solutions_api_integration/management/commands/tests/test_migrate_orgdata.py
setup.py

fixed broken org reference

---

edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/groups/tests.py
edx_solutions_api_integration/groups/views.py
edx_solutions_api_integration/urls.py
edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py
setup.py

This PR has changes required in api_integration app related to renaming of projects app.
@ziafazal would please take a look?

YONK-346: update references of projects app to new name

---

edx_solutions_api_integration/management/commands/add_new_permissions.py
edx_solutions_api_integration/management/commands/tests/test_add_new_permissions.py

@ziafazal @fredsmith  This is a new pull request for company admin role

added new company admin creation script

---

edx_solutions_api_integration/groups/tests.py
edx_solutions_api_integration/groups/views.py

Fix for story [YONK-418]: Error in GroupsGroupsDetail api.

---

edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py

Fix for story [YONK-415]: Error occurs in users-courses-detail api

---

edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py

This PR added ability to enroll user by email in CoursesUsersList API to support YONK-548.
@ayesha-baig would you please review?

ziafazal/YONK-548: added ability to enroll user by email in CoursesUsersList API

---

edx_solutions_api_integration/courses/serializers.py
edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/urls.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/urls.py

This PR has changes to optimize response time of Courses List API. We are not using CourseOverview App to retrieve course information.

YONK-317: Update Courses List API to use CourseOverview App

---

edx_solutions_api_integration/test_utils.py

using SCORE_PUBLISHED signal to generate gradebook.
@ayesha-baig FYI.

using SCORE_PUBLISHED signal to generate gradebook

---

edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py

This PR has changes to allow unicode characters in first and last name of user.
Changes picked from this commit
https://github.com/edx-solutions/api-integration/commit/94ca38497873c9a95b1611e2309e2306fc6a7672

YONK-399: UsersDetail.post API should support unicode data in user name

---

edx_solutions_api_integration/courses/serializers.py
edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/urls.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/migrations/0002_auto_20170412_0316.py
edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py
edx_solutions_api_integration/utils.py

This PR has code refactoring to optimize response time of different APIs. This YONK tickets has details of APIs to optimize
https://openedx.atlassian.net/browse/YONK-581
https://openedx.atlassian.net/browse/YONK-582
https://openedx.atlassian.net/browse/YONK-589
https://openedx.atlassian.net/browse/YONK-593
@ayesha-baig would you please review?

Optimizations for social metrics APIs

---

edx_solutions_api_integration/courses/tests.py

fixed broken test

---

edx_solutions_api_integration/courses/content.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/test_utils.py
edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py

fixed broken unit tests after ficus upgrade
replaced  SCORE_PUBLISHED signal with PROBLEM_WEIGHTED_SCORE_CHANGED

Fixes for ficus upgrade

---

apiary.apib

This PR documents api-integration APIs, @ziafazal could you please review.
FYI @wajeeha-khalid

MCKIN-5070: Create apiary documentation for APIs

---

edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py

Improved the fault tolerance between the different services in the system.

YONK-603: Improved fault tolerance between the services

---

apiary.apib
edx_solutions_api_integration/users/serializers.py
edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/urls.py
edx_solutions_api_integration/users/views.py

User Progress list API to return progress of the user in enrolled courses.

YONK-703: User Progress list API

---

apiary.apib
edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py

Added a flag in user progress API for getting mobile enabled courses.

YONK-719: Added mobile course flag in user progress API

---

edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/users/serializers.py
edx_solutions_api_integration/utils.py

This PR has changes to optimize introduce course user grade, course user progress and course users list APIs.
To optimize these APIs we have reduced number of DB hits and introduce caching.
@aamishbaloch would you please review?

Optimized course user grade, course user progress and course users list APIs

---

edx_solutions_api_integration/courses/serializers.py
edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py

**complete_status** added in Passed Users API.

YONK-721: Complete Status added in Passed Users API

---

edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/urls.py
edx_solutions_api_integration/courses/views.py

APIs are updated and optimised using course blocks.

YONK-15: API optimisations using course blocks

---

apiary.apib

This PR updates apiary doc for course passed users api to include `complete_status` attribute

update apiary doc for course passed users api

---

edx_solutions_api_integration/courses/views.py

Course Blocks API fix to get all included fields added in the request.

YONK-738: Course Blocks API updates

---

edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py

User update API allowed to set following attributes as NULL
- country
- city
- gender

YONK-742: User update API allowed to set country,city & gender as NULL

---

edx_solutions_api_integration/mobile_api/tests/test_users.py
edx_solutions_api_integration/mobile_api/urls.py
edx_solutions_api_integration/mobile_api/views.py
edx_solutions_api_integration/permissions.py
edx_solutions_api_integration/urls.py
edx_solutions_api_integration/users/views.py
edx_solutions_api_integration/utils.py

This PR has changes which add a new endpoint to get all organizations a user is member of. This endpoint is expected to be consumed by mobile clients.
@msaqib52 FYI.

added endpoint for user ogranizations API

---

apiary.apib
edx_solutions_api_integration/mobile_api/urls.py
edx_solutions_api_integration/mobile_api/views.py
edx_solutions_api_integration/users/views.py

This PR includes Oauth support for user course progress API.

YONK-750: Oauth support for user course progress API

---

apiary.apib
edx_solutions_api_integration/mobile_api/tests/test_courses.py
edx_solutions_api_integration/mobile_api/urls.py
edx_solutions_api_integration/mobile_api/views.py
edx_solutions_api_integration/permissions.py

Changes include Oauth support for course overview API.

YONK-747: Oauth support for course overview API

---

apiary.apib
edx_solutions_api_integration/mobile_api/urls.py
edx_solutions_api_integration/mobile_api/views.py
edx_solutions_api_integration/users/views.py

Changes include Oauth support for users-courses-details APIs.

YONK-751: Oauth support for users-courses-details APIs

---

apiary.apib
edx_solutions_api_integration/courses/urls.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/mobile_api/urls.py
edx_solutions_api_integration/mobile_api/views.py

changes include Oauth support for resources API.

YONK-748: Oauth support for resources API

---

edx_solutions_api_integration/users/tests.py

Test updated for new changes in User Course Details API

test updated

---

edx_solutions_api_integration/mobile_api/tests/test_users.py
edx_solutions_api_integration/mobile_api/views.py

A cohort in this context is the group of users enrolled in the course, not the technical meaning of cohort we attribute in the codebase. This fixes the grades average calculation to include every user enrolled in the course, rather than just the course's cohort.
**JIRA Ticket**: [OC-2886](https://tasks.opencraft.com/browse/OC-2886)
1. Set up OAuth client in LMS admin if you don't already have one set up.
2. Obtain OAuth access token for your test user: curl -X POST -d "client_id={client_id}&client_secret={client_secret}&grant_type=password&username={username}&password={password}" https://lms.apros.local/oauth2/access_token/
3. Verify that you can access the api with your OAuth access token: curl 'http://lms.mcka.local/api/server/mobile/v1/users/courses/grades?user …

Fix the cohort average grade calculation in the MobileUsersCoursesGrades endpoint

---

edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/receivers.py

This PR has changes to reduce database hits when we call course metrics, cities metrics and social metrics APIs. 

Further optimizations to city, course and social metrics apis

---

edx_solutions_api_integration/management/commands/migrate_profile_images.py

This PR has changes in migrate profile image command to include AWS key and secret as arguments and update `profile_image_uploaded_at` field to generated appropriate paths for profile images.

Improved image migrate command to include aws key and secret

---

edx_solutions_api_integration/users/views.py
setup.py

This PR has changes to add mobile_available fields to courses progress API.

added mobile_available fields to courses progress api

---

edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/groups/views.py
edx_solutions_api_integration/users/views.py

some apis are modified to reduce database queries. related stories are YONK-763, YONK-764, YONK-765, YONK-766

YONK-530: API Performance

---

edx_solutions_api_integration/management/commands/migrate_profile_images.py
setup.py

Fixed a bug with image migration command

Fixed a bug with image migration command

---

edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/utils.py
setup.py

This PR has changes to make default image urls absolute. [YONK-781](https://openedx.atlassian.net/browse/YONK-781) has details of requirements.

YONK-781: Make default image urls absolute

---

apiary.apib
edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py

This PR has changes to add `users_passed` metric to course metrics API.

YONK-784: added users_passed metric to course metrics API

---

edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py

This PR has changes to add `avg_progress` and `avg_grade` metrics to course metrics API. 
@ihtram could you please review this?

YONK-802: add avg_progress and avg_grade to Course metrics API

---

edx_solutions_api_integration/mobile_api/tests/test_users.py
edx_solutions_api_integration/mobile_api/views.py

While persistent grades are disabled, use `StudentGradebook` instead of `CourseGradesFactory` to calculate user and course average grades.
`StudentGradebook` is what the current Courses and User APIs use to fetch grades.
**JIRA tickets**: [MCKIN-6328](https://edx-wiki.atlassian.net/browse/MCKIN-6328), OC-3302
**Setup instructions**:
1. Checkout this branch on your solutions devstack under `/edx/bin/api-integration`
1. Install it:
```bash
edxapp@precise64:/edx/src/api-integration$ pip install -e .
```
1. Run the LMS without installing prerequisites:
```bash
edxapp@precise64:~/edx-platform$ NO_PREREQ_INSTALL=1 paver run_all_servers --settings=devstack
```
Manual instructions:
1. Create a course with one or more graded subsections, containing problems.
1. Enrol 2 …

MCKIN-6328 Improve MobileUsersCoursesGrades performance

---

edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py

This PR refactored code around users list and course details APIs. Refactoring in users list API allow us to search users when partial search is enabled and multiple course ids are provided whereas refactoring on course details API removed unnecessary depth parameter to improve its performance.

YONK-810: Refactored users list and course details APIs

---

apiary.apib
edx_solutions_api_integration/permissions.py
edx_solutions_api_integration/test_utils.py
edx_solutions_api_integration/urls.py
edx_solutions_api_integration/utils.py

These changes are done to integrate **`mobileapps-edx-platform-extensions`** with API integration and Platform. Changes include addition of mobile app url, with some new permissions used in mobile apps and an extension to Username Cipher for encryption of secret keys used for mobile apps.
UPDATE: **`SecureAPIView`** is now inherited by **`PermissionMixin`** to enforce more security to our views.
UPDATE: Documentation of mobile app management APIs added.

YONK-791: Mobile app Detail & List APIs with Unit Tests

---

edx_solutions_api_integration/permissions.py

Mobile Permissions added for enabling oAuth2 for mobile app configuration APIs.

YONK-811: Mobile Permissions added for oAuth2

---

edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/mobile_api/views.py
edx_solutions_api_integration/permissions.py

Added Oauth Support to Course Detail view.

YONK-826: Added Oauth Support to Course Detail view

---

apiary.apib
edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/users/serializers.py
setup.py

Changes include addition of progress to CoursesUsersList.

YONK-828: Added progress to CoursesUsersList

---

apiary.apib
edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/users/serializers.py
edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py
setup.py

Changes include modified User API to include list of enrolled courses instead of count.

YONK-836: Modified User API to include list of enrolled courses

---

apiary.apib
edx_solutions_api_integration/permissions.py
setup.py

Changes include IsStaffOrReadOnlyView permission added for mobileapp themes POST/UPDATE views. API documentation is added also.

YONK-829: IsStaffOrReadOnlyView permission added

---

apiary.apib
edx_solutions_api_integration/mobile_api/serializers.py
edx_solutions_api_integration/mobile_api/tests/test_users.py
edx_solutions_api_integration/mobile_api/views.py
setup.py

Changes include addition of mobile apps & themes detail added in organization API.

YONK-837: Mobile apps & themes detail added in organization API

---

apiary.apib
setup.py

YONK-845: Header Background Image added in organization theme

---

edx_solutions_api_integration/mobile_api/tests/test_users.py
setup.py

Changes include addition of ios_bundle_id added in users organizations. Relative unit test updated.

YONK-851: ios_bundle_id added in users organizations

---

apiary.apib

Changes include documentation for Course Settings updated.

YONK-852: Documentation updated

---

apiary.apib
edx_solutions_api_integration/mobile_api/tests/test_users.py
edx_solutions_api_integration/users/views.py
setup.py

Changes include addition of mobile flag & languages in user courses API

YONK-862: Mobile flag & languages added in user courses API

---

apiary.apib
edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/mobile_api/tests/test_users.py
edx_solutions_api_integration/users/serializers.py
edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py
setup.py

Changes include addition of language in Course Detail and Progress APIs. Only single language will be returned.

YONK-868: Course will have a single language

---

apiary.apib
edx_solutions_api_integration/permissions.py
setup.py

Changes include addition of new permissions to facilitate new APIs and API doc updated with the new API of remove images of mibile themes.

YONK-876: New permissions added and API doc updated

---

edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py
setup.py

Changes include a fix of the issue in [YONK-921](https://openedx.atlassian.net/browse/YONK-921).

Analytics page issue fixed

---

edx_solutions_api_integration/courses/urls.py
edx_solutions_api_integration/courses/views.py
setup.py

Changes include Oauth2 implementation on block detail view.

YONK-924: Oauth2 fix

---

edx_solutions_api_integration/courses/urls.py
edx_solutions_api_integration/courses/views.py
setup.py

Changes include removal of Xblock handler API

YONK-924: Xblock handler API removed

---

edx_solutions_api_integration/courses/serializers.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/users/serializers.py
setup.py

Changes include progress percentage consistency in api-integration and platform.

YONK-952: Progress % consistency

---

edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py
setup.py

Changes include support to search user on first-name and last-name in Users List API

YONK-966: User API to support search on first-name and last-name

---

edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py
setup.py

Changes include User API to support search on first-name and last-name and full name also.

YONK-966: User API to support search on full name also

---

edx_solutions_api_integration/users/serializers.py
edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py
setup.py

Changes include addition of proficiency in User Progress API. Course filter is added aditionally to the API.

YONK-997: Proficiency added in User Progress API

---

edx_solutions_api_integration/users/views.py
setup.py

Changes include course activeness filter added in User Progress API. Filter is optional.

YONK-997: Course activeness filter in User Progress API

---

edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/urls.py
edx_solutions_api_integration/users/views.py

Changes include view to add/update values for user against Organisation Fields

YONK-1025: Update single user information (Organisation Field Values)

---

edx_solutions_api_integration/mobile_api/tests/test_users.py
edx_solutions_api_integration/permissions.py
edx_solutions_api_integration/test_utils.py
edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/urls.py
edx_solutions_api_integration/users/views.py

Bearer token based user details API created

YONK_1067: Verify Bearer Token

---

README.rst
apiary.apib
edx_solutions_api_integration/courses/serializers.py
edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/urls.py
edx_solutions_api_integration/courses/utils.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/courseware_access.py
edx_solutions_api_integration/management/commands/bulk_delete_courses_with_reference_data.py
edx_solutions_api_integration/management/commands/tests/test_bulk_delete_courses_with_reference_data.py
edx_solutions_api_integration/test_utils.py
edx_solutions_api_integration/users/serializers.py
edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/urls.py
edx_solutions_api_integration/users/views.py
setup.py

Make api-integration use the completion V1 API.
**JIRA tickets**: OC-4523 / MCKIN-7755
**Dependencies**: None
**Reviewers**

[MCKIN-7755] [OC-4523] Port to completion API v1

---

apiary.apib
edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/permissions.py
edx_solutions_api_integration/users/serializers.py
edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/urls.py
edx_solutions_api_integration/users/views.py
edx_solutions_api_integration/utils.py
setup.py

Changes include IsOpsAdminOrReadOnlyView added to check if the user is course ops admin and the view is POST.

YONK-1010: New Permission added

---

edx_solutions_api_integration/users/tests.py

Changes to the tests as the keys were randomized.
[YONK-1151]

Delete organization field API issues

---

setup.py

Setup.py version update for release

---

edx_solutions_api_integration/users/views.py

This PR is connected with [this](https://github.com/edx-solutions/discussion-edx-platform-extensions/pull/20).

[MCKIN-8418] Optimize UsersSocialMetrics.get API

---

edx_solutions_api_integration/courses/utils.py
edx_solutions_api_integration/courses/views.py
setup.py

@UmanShahzad, this PR is a part of `[MCKIN-8491]` PR-s.

[MCKIN-8491] Engagement score average reflective of Discussion activity by Cohort Group

---

edx_solutions_api_integration/courses/urls.py
edx_solutions_api_integration/courses/utils.py
edx_solutions_api_integration/courses/views.py

@UmanShahzad, this PR is a part of `[MCKIN-8511]` PR-s.

[MCKIN-8511] Optimize - Course cohort page - API

---

edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/courseware_access.py
edx_solutions_api_integration/imports/__init__.py
edx_solutions_api_integration/imports/urls.py
edx_solutions_api_integration/imports/views.py
edx_solutions_api_integration/mobile_api/views.py
edx_solutions_api_integration/permissions.py
edx_solutions_api_integration/urls.py
edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py
setup.py

[MCKIN-8530] Optimize Imports Participants API

---

edx_solutions_api_integration/users/views.py
setup.py

This is a part of [this PR](https://github.com/edx-solutions/discussion-edx-platform-extensions/pull/25). It disables caching as requested in the ticket.

[MCKIN-8714] Disable caching social metrics

---

edx_solutions_api_integration/courses/views.py

This PR is a part of `[MCKIN-7951]` PR-s.

[MCKIN-7951] Optimize CoursesDetail API

---

edx_solutions_api_integration/groups/tests.py
edx_solutions_api_integration/groups/views.py
setup.py

add support for linking multiple user to a group in groups users api

MCKIN-8764: add support for linking multiple user to a group in groups users api

---

edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/permissions.py
edx_solutions_api_integration/users/serializers.py
edx_solutions_api_integration/utils.py
setup.py

[MCKIN-8780] Optimize CoursesUsersList.get

---

edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/users/views.py
setup.py

This PR reverts [MCKIN-8730] and [MCKIN-8418].
Test whole discussions for users and admin.

Revert [MCKIN-8730] and [MCKIN-8418]

---

edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/users/views.py
setup.py

This reverts the last reverts (#167).

Revert "Revert [MCKIN-8730] and [MCKIN-8418] (#167)"

---

edx_solutions_api_integration/imports/views.py
setup.py

This PR is part of [MCKIN-8718].

[MCKIN-8718] Optimize Enroll existing Participants API

---

edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py

get queryset of updated partial search

get queryset of updated partial search

---

setup.py

This PR bumps version to 2.3.5

MCKIN-8585-b: bump version to 2.3.5

---

edx_solutions_api_integration/courses/utils.py
edx_solutions_api_integration/courses/views.py
setup.py

This PR disables the feature implemented by MCKIN-8502.

[MCKIN-8502] Revert

---

setup.py

Didn't rebase so the bump I did earlier became redundant and disappeared on merge. Bumping again.

[MCKIN-8963] Bump.

---

edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/users/views.py
setup.py

This PR reverts cohort average scores and optimizations to social metrics API.

Revert [MCKIN-8730] [MCKIN-8418] [MCKIN-8502]

---

edx_solutions_api_integration/imports/views.py
setup.py

[MCKIN-8977] Retry getting the cohort.

---

edx_solutions_api_integration/users/serializers.py
edx_solutions_api_integration/users/views.py

fixed enrolled courses count and course participant search impact

fixed enrolled courses count and course participant search impact

---

edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/users/views.py
edx_solutions_api_integration/utils.py
setup.py

This PR implement Waffle flags to disable cohort average scores.

[MCKIN-9040] Cohort average scores behind waffle flag

---

edx_solutions_api_integration/utils.py
setup.py

Removed filter for empty values.
[YONK-1216](https://openedx.atlassian.net/browse/YONK-1216)

Implemented fix for YONK-1216

---

edx_solutions_api_integration/imports/views.py
setup.py

This PR is connected with MCKIN-8977 ticket.

[MCKIN-8977] Fix race condition during importing participants

---

edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py
setup.py

Optimized course filtering for course participants search.

MCKIN-9179 - Optimized course participants search - course filtering.

---

edx_solutions_api_integration/courses/urls.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/users/views.py
setup.py

MCKIN-9405 MCKIN-9125
Added course image and number of chapters to `/api/users/{user_id}/courses/` endpoint
`/api/users/{user_id}/courses/` endpoint should also return `course_image_url` and `total_chapters`

[MCKIN-9405][MCKIN-9125]Added course image and number of chapters to UsersCoursesList

---

edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py
setup.py

MCKIN-8918
Part of https://github.com/edx-solutions/edx-platform/pull/1361

MCKIN-8918 Retire discussion users

---

edx_solutions_api_integration/courses/serializers.py
edx_solutions_api_integration/courses/utils.py
setup.py

MCKIN-9976 -- Added user first and last name

MCKIN-9976 -- Added user first and last name

---

edx_solutions_api_integration/users/views.py
setup.py

[MCKIN-9402] Implement bulk deletion

---

edx_solutions_api_integration/users/views.py
setup.py

Remove upper bound limit for internal course_ids

[MCKIN-9794] removed-upper-bound-limit-for-internal-course_ids

---

edx_solutions_api_integration/users/tests.py
edx_solutions_api_integration/users/views.py
setup.py

This PR relays errors during deletion of users.
Part of https://github.com/edx-solutions/edx-platform/pull/1422

[MCKIN-10190] Relay errors in user deletion

---

edx_solutions_api_integration/users/serializers.py
setup.py

MCKIN-10068 -- added last login time-date

MCKIN-10068 -- added last login time-date

---

edx_solutions_api_integration/users/views.py
setup.py

Optimized filter for internal admin

Filter optimized for internal admin

---

edx_solutions_api_integration/users/views.py
setup.py

Profile image gets broken whenever we edit the username
The issue is fixed by renaming the uploaded image files for all four sizes according to the new username.

issue fixed

---

edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/test_utils.py
edx_solutions_api_integration/urls.py
edx_solutions_api_integration/users/views.py
setup.py

This reverts commit cb102cc2de5e4a7177f61cad74aafa06db1e0fe9.

Revert "[MCKIN-7759] PR #208"

---

edx_solutions_api_integration/users/views.py
setup.py

Email field will perform case insensitive search if a user searches participants via this field

MCKIN-10458 - Email field set to be case insensitive

---

edx_solutions_api_integration/courses/urls.py
edx_solutions_api_integration/courses/views.py
setup.py

Moving CoursesTree API post that it doesn't halt on a large number of courses.

MCKIN-10546-make course tree api post

---

edx_solutions_api_integration/users/views.py
setup.py

Moving DB query to get_or_create so that it can't be one operation.

MCKIN-10858

---

edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/test_utils.py
edx_solutions_api_integration/urls.py
edx_solutions_api_integration/users/views.py
setup.py

Redo of https://github.com/edx-solutions/api-integration/pull/208

 [MCKIN-7759] Remove usage of CourseAggregatedMetaData since it is no longer in use.

---

edx_solutions_api_integration/users/views.py
setup.py

Handled activation page error message issue

Mckin 10968 handled activation page error message issue

---

setup.py

The updated version for handling activation page error message issue

MCKIN-10968 version updated to 3.1.2

---

edx_solutions_api_integration/management/commands/cs_sync_user_info.py
edx_solutions_api_integration/tasks.py
setup.py

Modified management command version of https://github.com/edx-solutions/edx-platform/blob/master/lms/djangoapps/django_comment_client/management/commands/sync_user_info.py to handle exceptions and include logging

MCKIN-10967 management command for cs user info sync

---

edx_solutions_api_integration/courses/utils.py
edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/utils.py
setup.py

Fixed discrepancy in average progress for engaged people

MCKIN-9592 - Discrepancy in average progress for engaged people

---

edx_solutions_api_integration/management/commands/convert_ooyala_embeds.py
edx_solutions_api_integration/tasks.py
edx_solutions_api_integration/templates/bcove_html_embed.html
edx_solutions_api_integration/templates/bcove_ie_embed.html
setup.py

Script for converting Ooyala embeds in raw html and image explorer xblocks to associated Brightcove embed.

MCKIN-11426 - convert ooyala embeds in raw html and image explorer

---

edx_solutions_api_integration/tasks.py
setup.py

Adding more blocks as Ooyala embed can be authored in these blocks

MCKIN-12100 - Ooyala embed conversion different blocks

---

edx_solutions_api_integration/management/commands/convert_ooyala_embeds.py
edx_solutions_api_integration/management/commands/convert_ooyala_ids_to_bcove.py
edx_solutions_api_integration/tasks.py
setup.py

- Groupwork video resource block also added in conversion script
- `pb-mrq` and `pb-answer` added in conversion blokcs
- Support for multiple course ids in migration script
- Blocks retrieval option limited to `published_only`

MCKIN-12100 - Convert Ooyala group work video resource

---

edx_solutions_api_integration/templates/bcove_html_embed.html
edx_solutions_api_integration/templates/bcove_ie_embed.html
setup.py

`playsinline` attribute added in embed to support Safari inline video playback

MCKIN-12605 - playsinline attribute added in embed 

---

edx_solutions_api_integration/tasks.py
setup.py

Catched another potential exception

Exception handling fix

---

edx_solutions_api_integration/templates/bcove_html_embed.html
edx_solutions_api_integration/templates/bcove_ie_embed.html
setup.py

`playsinline` without a value causes syntax error in `ImageExplorer`

MCKIN-12605 - playsinline fix to prevent xml syntax error

---

edx_solutions_api_integration/imports/views.py
edx_solutions_api_integration/models.py
edx_solutions_api_integration/sessions/views.py
edx_solutions_api_integration/test_password_history.py
edx_solutions_api_integration/users/test_user_password_reset.py
edx_solutions_api_integration/users/views.py

Password History Model and its tests moved to api-integration from openedX.

Move PasswordHistoryModel into api-integration from openedX.

---

edx_solutions_api_integration/tasks.py
setup.py

Static tabs which are used to create course resources page is also added in Bcove migration script

MCKIN-12647 - static tabs added in conversion script

---

edx_solutions_api_integration/courses/views.py

Comment out the rebase changes that is changed in according to iron-wood

Rebase Course structure changes.

---

edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/tasks/convert_ooyala_to_bcove.py
setup.py

- Script can be run on all courses from API
- Courses can be excluded from script by passing in `exclude_course_ids`

MCKIN-12729 - Conversion script API enhancements

---

MANIFEST.in
setup.py

- `templates` directory added to manifest file so it get included in installed package

YONK-1547 - Manifest file update

---

edx_solutions_api_integration/templates/bcove_html_embed.html
setup.py

`playsinline` attribute is removed to mimic the behavior of Ooyala Player

MCKIN-12762 - playsinline attribute removal

---

edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/sessions/views.py
edx_solutions_api_integration/tasks/convert_ooyala_to_bcove.py
setup.py

This task pulls list for all video instances in given course ids

MCKIN-12823 - task for list of video modules

---

edx_solutions_api_integration/tasks/convert_ooyala_to_bcove.py
edx_solutions_api_integration/templates/bcove_html_embed.html
setup.py

- Added `playsinline` back in BC template
- Modified get video module list

Modified get video module list

---

edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/tasks/get_assets_with_incorrect_urls.py
setup.py

If an asset link points to some other server or course try to replace with the identical asset if it exists in the same course, otherwise log a descriptive message so asset could be manually uploaded.

MCKIN-13352 - Script to update incorrect assets urls

---

edx_solutions_api_integration/tasks/convert_ooyala_to_bcove.py
setup.py

- Increased results cache timeout to cater long running tasks
- Added except clause for update cache method
- block location retrieval safeguarded

MCKIN-13525 - Consolidate exception handling in O2B task

---

edx_solutions_api_integration/courses/test_courses.py
edx_solutions_api_integration/groups/test_groups.py
edx_solutions_api_integration/sessions/test_security.py
edx_solutions_api_integration/sessions/test_sessions.py
edx_solutions_api_integration/test_permissions.py
edx_solutions_api_integration/users/test_user_password_reset.py
edx_solutions_api_integration/users/test_users.py
edx_solutions_api_integration/users/views.py

removed ENFORCE_PASSWORD_POLICY feature flag as it is deprecated in Ironwood release

YONK-1585 - Remove deprecated feature flags in Ironwood

---

edx_solutions_api_integration/tasks/get_assets_with_incorrect_urls.py
setup.py

- Updates to tackle instances inside the list

MCKIN-13352 - updates in incorrect assets url script

---

edx_solutions_api_integration/courses/views.py
setup.py

- Removed unnecessary nested loop.
- Removed `.copy()` on blocks.
- Moved logic to find course block to a new function to avoid iterating all of the blocks

MCKIN-14035 Optimized course tree API

---

edx_solutions_api_integration/courses/utils.py
edx_solutions_api_integration/courses/views.py
setup.py

Fixed avg progress which was getting issued for few courses due to the different order of calculating progress even if rounds off correctly.

MCKIN-13560 fix Avg Progress difference

---

edx_solutions_api_integration/courses/utils.py
edx_solutions_api_integration/courses/views.py
setup.py

reverting MCKIN-13560 for now, will push it back later.

reverting MCKIN-13560

---

edx_solutions_api_integration/mobile_api/views.py

reverting MCKIN-14037, these changes will be added later by @naeem91 .

reverting MCKIN-14037

---

edx_solutions_api_integration/courses/tests.py
edx_solutions_api_integration/courses/utils.py
edx_solutions_api_integration/courses/views.py
setup.py

Fixed avg progress which was getting issued for few courses due to the different order of calculating progress even if rounds off correctly.

MCKIN-13560 Avg Progress difference

---

edx_solutions_api_integration/mobile_api/views.py
setup.py

This PR adds following improvements:
- Mobile endpoint now uses same code and caching as web endpoint
- Staff members are excluded from average score calculation as web

MCKIN-14037 - proficiency score caching for mobile api

---

edx_solutions_api_integration/tasks/get_assets_with_incorrect_urls.py
setup.py

Split mongo courses excluded from processing

MCKIN-12722 - Split mongo courses excluded from processing

---

edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/users/views.py
edx_solutions_api_integration/utils.py
setup.py

Fix participant count on company details and company course details page.

MCKIN-14231 fix participants count

---

edx_solutions_api_integration/tasks/get_assets_with_incorrect_urls.py
setup.py

- Added exception handling to safeguard block update
- Added proper studio urls 
- Fetch only published units

MCKIN-13352 - Assets URLs script consolidation

---

edx_solutions_api_integration/courses/views.py
setup.py

Added cache and some refactoring in CoursesMetrics API.
- Course enrollment count, course grade, course progress, passed and completed count were retrieved from db every time. Now it is get from cached. DB Queries are now reduced from 13 to 5 in case of a warm cache.

MCKIN-16266 -  Optimize CoursesMetrics API

---

edx_solutions_api_integration/tasks/get_assets_with_incorrect_urls.py
setup.py

Fixed the asset URL condition to include organization also.

MCKIN-13352 - Fixed asset url condition

---

edx_solutions_api_integration/tasks/get_assets_with_incorrect_urls.py
setup.py

MCKIN-13352 - fixed asset url condition (#281)

---

edx_solutions_api_integration/courses/urls.py
edx_solutions_api_integration/courses/views.py
setup.py

- Created a new API to retrieve course average scores in a more cleaner way. 
- Usage of this API reduces extra DB queries for getting average progress
Related Apros PR: https://github.com/mckinseyacademy/mcka_apros/pull/3782

MCKIN-16946 - Optimize course average progress retreival

---

edx_solutions_api_integration/users/views.py
setup.py

mark missing string for translation

MCKIN-19205: mark string for translation

---

edx_solutions_api_integration/courses/utils.py
setup.py

- Filtered Aggregators with zero percentage.

[MCKIN-20588] Fix for completion leaderboard

---

edx_solutions_api_integration/management/commands/send_progress_leaderboard_notifications.py

https://edx-wiki.atlassian.net/browse/MCKIN-20811
In this PR user with is_staff or ta or observer role will be restricted from Notification

MCKIN-20811 Notification - TA/staff are receiving notifications

---

edx_solutions_api_integration/courses/views.py
setup.py

Introduced a post method to avoid issues with URL size limitation.

MCKIN-24492 post method to avoid request limit

---

edx_solutions_api_integration/users/views.py
setup.py

Introduced bulk delete roles to avoid request time out.

MCKIN-24501 bulk delete role management

---

edx_solutions_api_integration/imports/views.py
setup.py

Returning user id in case of enrolling existing users
related PR is https://github.com/mckinseyacademy/mcka_apros/pull/3951

MCKIN-24786

---

edx_solutions_api_integration/courses/test_courses.py
edx_solutions_api_integration/courses/utils.py
edx_solutions_api_integration/courses/views.py
setup.py

This PR fixes course average progress calculation and uses single formula to for calculation to remove discrepancies created during rounding off.

MCKIN-28999: fix course average progress calculation

---

edx_solutions_api_integration/users/views.py

if user is not enrolled in the course, return appropriate error message.

MCKIN-29488 Returning error message when student is not enrolled in course

---

edx_solutions_api_integration/users/views.py

Synced user info with discussion service on updating first_name, last_name or username.

MCKIN-30999 sync user info with comment service

---

edx_solutions_api_integration/users/views.py
setup.py

Moving development [commit](https://github.com/edx-solutions/api-integration/commit/286ee05dd1de86bcbe2ff413ab0a52583ddaf50f#) to master.

MCKIN-30999 to master: sync user info with comment service

---

edx_solutions_api_integration/users/views.py

As a part of [MCKIN-31645](https://edx-wiki.atlassian.net/browse/MCKIN-31645), merging #322 to master.

Merging MCKIN-29488 to master

---

setup.py

MCKIN-29488 - Version bump

---

edx_solutions_api_integration/courses/views.py
edx_solutions_api_integration/users/serializers.py
setup.py

**Jira ticket**: [MEI-9862](https://mckinsey.atlassian.net/browse/MEI-9862)
Implements the code base changes to return user organization groups in user and course api.

MEI-9862 return users organization groups in user and course api
