edx-solutions/api-integration

- edx_solutions_api_integration/courses/tests.py
- edx_solutions_api_integration/courses/views.py
- setup.py
this PR has changes to support filtering users with certain roles in `CoursesMetricsCompletionsLeadersList` API. Roles can be filtered via `exclude_roles` query string. For example to exclude observer role from progress calculation we can pass a values like `exclude_roles=observer` and we don't want to apply any role filtering we can pass `exclude_roles=none` query string.
@msaqib52 would you please review.
> ziafazal/YONK-376: added ability to exclude users with certain roles

- edx_solutions_api_integration/courses/tests.py
- edx_solutions_api_integration/courses/views.py
- setup.py
This PR updates CoursesMetricsGradesLeadersList api to support filtering of users with certain roles. Roles can be filtered via exclude_roles query string. For example to exclude observer role we can pass values like exclude_roles=observer and if we don't want to apply any role filtering we can pass exclude_roles=none query string.
@ziafazal would you please review?
> YONK-377: adds ability to exclude users with certain roles

- edx_solutions_api_integration/management/commands/rename_api_manager_app.py
- setup.py
This PR wraps database operations around `transaction.commit_on_success` context manager to make sure changes are only committed when all statements are executed successfully.
@saleem-latif would you please review?
> added commit_on_success to context context manager

- edx_solutions_api_integration/management/commands/reverse_rename_api_manager_app.py
This PR has command to revert renaming of api_manager app.
@msaqib52 please review.
> command to revert renaming of api_manager app

- edx_solutions_api_integration/sessions/tests.py
- edx_solutions_api_integration/sessions/views.py
@ziafazal 
The checks have been added for both username and password and if any of these two is missing, HTTP_400_BAD_REQUEST response is sent. 
Also two unit tests are added for this change, one with the missing username and the other with missing password.
Here is the link of JIRA story;
https://openedx.atlassian.net/browse/YONK-421
> Fix for story [YONK-421]: Error in SessionsList api.

- edx_solutions_api_integration/courses/tests.py
- edx_solutions_api_integration/courses/views.py
@ziafazal 
A fix is added to send HTTP_400_BAD_REQUEST back in case 'group_id' is missing is request data. A unit test is also added for this fix.
https://openedx.atlassian.net/browse/YONK-425
> Fix for story [YONK-425]: Error in CoursesGroupsList api

- edx_solutions_api_integration/courses/tests.py
- edx_solutions_api_integration/courses/views.py
@ziafazal 
A fix has been added that in case of valid email provided in the request data, HTTP_204_NO_CONTENT should be sent. A unit test is also added to verify this change.
https://openedx.atlassian.net/browse/YONK-422
> Fix for story [YONK-422]: Error in CoursesUsersList api.

- edx_solutions_api_integration/groups/tests.py
- edx_solutions_api_integration/groups/views.py
@ziafazal 
A check is added that if course_id is missing in the request data, HTTP_400_BAD_REQUEST is sent back. Also a unit test is added to verify this change.
https://openedx.atlassian.net/browse/YONK-420
> Fix for story [YONK-420]: Error in GroupsCoursesList api.

- edx_solutions_api_integration/users/tests.py
- edx_solutions_api_integration/users/views.py
@ziafazal 
A check is added that if group_id field is missing in request or is empty, HTTP_400_BAD_REQUEST is responded back. The corresponding unit test is also added to verify the change.
https://openedx.atlassian.net/projects/YONK/issues/YONK-455
> Fix for story [YONK-455]: Error in UsersGroupsList api.

- edx_solutions_api_integration/users/tests.py
- edx_solutions_api_integration/users/views.py
@ziafazal 
A check is added that if given user_id does not exist, it should send HTTP_404_NOT_FOUND status code. Also a unit test is added for this change.
https://openedx.atlassian.net/projects/YONK/issues/YONK-456
> Fix for story [YONK-456]: Error in UsersGroupsDetail api.

- edx_solutions_api_integration/users/tests.py
- edx_solutions_api_integration/users/views.py
@ziafazal 
A check is added that if course_id is missing in request data or is empty HTTP_400_BAD_REQUEST is sent back. Also a unit test is added to verify the fix.
Here is the link to JIRA story;
https://openedx.atlassian.net/projects/YONK/issues/YONK-457
> Fix for story [YONK-457]: Error in UsersCoursesList api.

- edx_solutions_api_integration/courses/tests.py
- edx_solutions_api_integration/courses/views.py
@ziafazal 
A check is added to validate the format of start and end dates and HTTP_400_BAD_REQUEST should be sent back in case of invalid format. Also the unit tests are added to verify this fix.
https://openedx.atlassian.net/projects/YONK/issues/YONK-424
> Fix for story [YONK-424]: Error in CoursesTimeSeriesMetrics api.

- edx_solutions_api_integration/courses/tests.py
- edx_solutions_api_integration/courses/views.py
@ziafazal 
A code change is made so that it checks if course_content is None before accessing that field. Also the corresponding unit test is added to verify this change.
https://openedx.atlassian.net/projects/YONK/issues/YONK-423
> Fix for story [YONK-423]: Error in CoursesUsersDetail api.

- edx_solutions_api_integration/users/tests.py
- edx_solutions_api_integration/users/views.py
@ziafazal 
A check is added so that if "read" is missing in the request data, HTTP_400_BAD_REQUEST should be sent back. Also the unit test is added to verify the change.
https://openedx.atlassian.net/projects/YONK/issues/YONK-460
> Fix for story [YONK-460]: Error in UsersNotificationsDetail api.

- edx_solutions_api_integration/users/tests.py
- edx_solutions_api_integration/users/views.py
@ziafazal 
The code is changed to check if "roles" is missing in the request body or the "course_id" is missing in the corresponding role. Also the unit tests are added to verify the change.
Here is the link of the JIRA story;
https://openedx.atlassian.net/projects/YONK/issues/YONK-459
> Fix for story [YONK-459]: Error in UsersRolesList api.

- edx_solutions_api_integration/users/tests.py
- edx_solutions_api_integration/users/views.py
@ziafazal 
A change has been made so that if email, username or password are not provided in the request data, HTTP_400_BAD_REQUEST is sent back. The corresponding unit tests for these fields are also added.
https://openedx.atlassian.net/projects/YONK/issues/YONK-454
> Fix for story [YONK-454]: Error in UsersList api.

- edx_solutions_api_integration/users/tests.py
@ziafazal:
A unit test has been added to verify the fix which is made in the gradebook app. (In gradebook app, changes are made to handle the integrity error with the get_or_create method which occurred at the create function if the object existed already in the database)
https://openedx.atlassian.net/projects/YONK/issues/YONK-388
> Story [YONK-388]: Integrity Error in New Relic.

- edx_solutions_api_integration/users/tests.py
- edx_solutions_api_integration/users/views.py
@ziafazal 
The code has been changed to properly handle unicode data in first and last names. Also the unit test is added to test the change.
Here is the link of the JIRA story;
https://openedx.atlassian.net/projects/YONK/issues/YONK-399
> YONK-399: UsersDetail.post API should support unicode data in user name

- apiary.apib
This PR documents API required for building certificates at Apros. Apros admin will call this API documented in this PR on course end date to get list of all passing participants for the specified course and generate certificates for those users on apros side.
> document APIs required for building certificates at Apros

- edx_solutions_api_integration/courses/tests.py
- edx_solutions_api_integration/courses/views.py
In case of Course (Parent), ID should be generated by course_block in _make_block_tree.
> YONK-15: API optimisations using course blocks

- edx_solutions_api_integration/mobile_api/tests/test_users.py
- edx_solutions_api_integration/mobile_api/urls.py
- edx_solutions_api_integration/mobile_api/views.py
- edx_solutions_api_integration/permissions.py
- edx_solutions_api_integration/users/tests.py
- edx_solutions_api_integration/users/views.py
Implements mobile API with OAauth support for engagement. It also adds user's engagement score and course average engagement score to the API response.
It uses https://github.com/edx-solutions/discussion-edx-platform-extensions to fetch persisted engagement scores to avoid having to calculate course average score on-the-fly.
**JIRA tickets**: MCKIN-5311
**Dependencies**:
- https://github.com/edx-solutions/discussion-edx-platform-extensions/pull/10
1. Install code from https://github.com/edx-solutions/discussion-edx-platform-extensions/pull/10 into your virtual environment.
2. Enable https://github.com/edx-solutions/discussion-edx-platform-extensions on your devstack by adding `'ENABLE_SOCIAL_ENGAGEMENT': True` to your `FEATURES` in `lms.env.json`.
3. Verify that …
>  MCKIN-5311: Implement mobile API for engagement.

- apiary.apib
- edx_solutions_api_integration/courses/serializers.py
- edx_solutions_api_integration/courses/tests.py
- edx_solutions_api_integration/courses/urls.py
- edx_solutions_api_integration/courses/views.py
- edx_solutions_api_integration/migrations/0002_auto_20170412_0316.py
- edx_solutions_api_integration/users/tests.py
- edx_solutions_api_integration/users/views.py
- edx_solutions_api_integration/utils.py
- setup.py
This PR has changes required to optimize course metrics and social metrics APIs. Changes also introduce a new CoursesMetricsSocialLeadersList view to get course leaders by their social engagement score.
Details of the implementation can be found in YONK-580.
> optimize course metrics and social metrics APIs

- edx_solutions_api_integration/courses/views.py
- edx_solutions_api_integration/users/views.py
Prevents LMS from raising 500 when queried for course content where a module may have no child content, and removes non-staff courses from module tree.
**JIRA tickets**: [OC-2999](https://tasks.opencraft.com/browse/OC-2999) [MCKIN-5434](https://edx-wiki.atlassian.net/browse/MCKIN-5434)
**Merge deadline**: None
1. Set up a course where a section is hidden from students (i.e. is staff-only content)
1. Log in as a non-staff user
1. The staff-only section is not visible in navigation, and if you navigate to the URL (that you can find before checking this branch out), it should 404 rather than 500.
**Author notes and concerns**:
Should I pass user along in the 2 other instances of `get_blocks()` in this file ([here](https://github.com/open-craft/api-integration/blob/a9 …
> prevent UsersCoursesDetail view from failing with 500

- edx_solutions_api_integration/users/views.py
This PR has little optimization to `UsersCoursesList.get` call which is calling courseoverview instead of hitting mongo for course info.
> YONK-777: Use courseoverview instead of hitting mongo getting course info

- edx_solutions_api_integration/courses/views.py
- setup.py
This PR has changes to fix `KeyError` when a user who has not access to course content try to call course details API. [YONK-778](https://openedx.atlassian.net/browse/YONK-778) has more details about the issue.
@aamishbaloch could you please review.
> YONK-778: Fix for error when user has not access to course blocks

- edx_solutions_api_integration/users/tests.py
- edx_solutions_api_integration/users/urls.py
- edx_solutions_api_integration/users/views.py
- setup.py
This creates a view that can be used by integration tests to create a user, active them, and enroll them in courses with a single API call.
* On a solutions devstack, update your `requirements/edx/custom.txt` to point to git+https://github.com/open-craft/api-integration.git@cliff/integration-test-user-creation#egg=api-integration==1.5.0a1`
* Post to /api/users/integration-test-users/ on solutions devstack with json post body:
```json
{
"username": "unused_username", 
"email": "email@address.com", 
"password": "fourlettersormore",
"courses": [
"some/valid/courses",
"course-v1:some+invalid",
"course-v1:some+nonexistent+courses"
]
}
```
* If the user already exists or cannot be created for some other reason, an error should be returned. Otherwise the user should be created.  You should be …
> Create view to create, activate, and enroll users for integration tests.

- edx_solutions_api_integration/users/views.py
This PR added if statement to avoid getting 'NoneType' object has no attribute 'id' error if a user is enrolled in a deleted course.
> added if statement to avoid error

- edx_solutions_api_integration/courses/serializers.py
- edx_solutions_api_integration/courses/tests.py
- edx_solutions_api_integration/courses/views.py
- edx_solutions_api_integration/users/serializers.py
- edx_solutions_api_integration/users/tests.py
- edx_solutions_api_integration/users/views.py
- edx_solutions_api_integration/utils.py
This PR has changes to return user's profile images instead of avatar_url in APIs which were returning `avatar_url`. This PR has changes to stop storing of `avatar_url` in user's profile model. [YONK-692](https://openedx.atlassian.net/browse/YONK-692) has details of requirements.
@aamishbaloch would you please review?
> YONK-692: return user's profile images instead of avatar_url in APIs

- edx_solutions_api_integration/courses/views.py
- edx_solutions_api_integration/utils.py
This PR has changes to introduce caching of leader boards APIs for large cohort size courses. To test call these apis in django rest framework with django toolbar enabled twice and notice for second call SQL query are zero.
http://lms.mcka.local/api/server/courses/orgx/{course_id}/metrics/completions/leaders?count=3&user_id={user_id}
http://lms.mcka.local/api/server/courses/orgx/{course_id}/metrics/grades/leaders?count=3&user_id={user_id}
http://lms.mcka.local/api/server/courses/orgx/{course_id}/metrics/social/leaders?count=3&user_id={user_id}
@aamishbaloch could you please review
> YONK-780: caching leaderboards for social, progress and proficiency metrics

- edx_solutions_api_integration/courses/tests.py
- edx_solutions_api_integration/courses/views.py
This PR has changes to add group filter support in course groups API by multiple group types. The `type` parameter in course groups API can be a comma separated list of group types to filter.
> YONK-803: added group filter support in course groups API by multiple group types

- edx_solutions_api_integration/courses/tests.py
- edx_solutions_api_integration/courses/views.py
This PR has changes to use course structure API inside course details API when we don't have user session since course blocks API does not use caching when we don't have a session. This would help reduce the API response time when it is called from apros.
> use course structure api when we don't have user session

- apiary.apib
- edx_solutions_api_integration/courses/serializers.py
- setup.py
This PR adds `mobile_available` field to `CourseSerializer ` to support YONK-839.
> YONK-839: added mobile_available field to course serializer

- edx_solutions_api_integration/mobile_api/serializers.py
- edx_solutions_api_integration/mobile_api/tests/test_users.py
- setup.py
Changes include Basic Mobileapp and theme serializers added to exclude Organization & user data in mobile apps and themes details in Organizations list API.
> YONK-837: Unnecessary data excluded in Organizations list API

- edx_solutions_api_integration/users/serializers.py
- edx_solutions_api_integration/users/test_serializers.py
- edx_solutions_api_integration/users/views.py
This pull request makes sure that the Progress value of the old API is the same as the new API.
**JIRA tickets**: MCKIN-6668
**Merge deadline**: "None"
1. For at least one course, inside Studio, set "Mobile Course Available" to "true" in Advanced Settings
2. Log into the Staff user.
3. Visit this course with the staff user in LMS and incur progress events.
4. Visit the URL /api/server/mobile/v1/users/courses/progress?username=staff 
5. Examine the "progress" value for each progress event.
6. Visit the URL /api/completion/v0/course/?mobile_only=true
7. Compare the "ratio" values with the "progress" values of the other API. The progress value should be 100x larger than the ratio value.
**Author notes and concerns**:
1. The way this fix works, is the new API is …
> [MCKIN-6668] Fix Mobile Progress Value

- edx_solutions_api_integration/courses/serializers.py
- setup.py
Changes include updating the OrganizationCourseSerializer that is used by Organization Courses API, to optimize the performance of the API.
> YONK-927: OrganizationCourseSerializer updated

- edx_solutions_api_integration/courses/tests.py
- setup.py
The `test_courses_completions_leaders` test is failing because it's checking the completion position of a user and getting the wrong result. The position is based on the number of completions and the modified time, and there are two users with the same number of completions, so it's essentially relying on the modified time of the aggregator which isn't something the test should rely on.
> Fix test_courses_completions_leaders test

- edx_solutions_api_integration/courses/tests.py
- edx_solutions_api_integration/courses/views.py
- edx_solutions_api_integration/users/serializers.py
- setup.py
Implements the changes to return the list of users' cohorts in the course API, controlled by the `additional_fields` querystring parameter.
**JIRA Tickets**: [MCKIN-8491](https://edx-wiki.atlassian.net/browse/MCKIN-8491)
**Discussions**: N/A
**Dependencies**: N/A
**Screenshots**: N/A
**Sandbox URL**: N/A
**Merge deadline**: 15 Oct 2018
**Testing instructions**: 
* Install the source branch of this PR in the `edx-solutions` devstack in the `edxapp` virtualenv.
* From the Apros Django shell, invoke the `get_course_details_users` method in the `api_client/course_api.py` file with the `additional_fields` querystring parameter having the value `course_groups`. The returned response should have a list of containing the users' cohort group for the given course.
**Reviewers**
> Return the list of users' cohorts in the users in course api

- setup.py
This updates the version in `setup.py` to 2.0.9, in order to tag and release the changes in https://github.com/edx-solutions/api-integration/pull/155.
I had updated the version from 2.0.7 to 2.0.8 in that PR. But there was already a tagged 2.0.8 release without an updated `setup.py`
**Reviewers**
> Update version to 2.0.9

- edx_solutions_api_integration/users/views.py
- setup.py
Reverts edx-solutions/api-integration#161 and part of #151.
1. Send
```bash
curl -X GET \
'http://localhost:8000/api/server/users/{user_id}/courses/{course_id}/metrics/social/?include_stats=true' \
-H 'X-Edx-Api-Key: edx_api_key'
```
with and without `include_stats` query param and verify it's working.
> Revert "[MCKIN-8714] Disable caching social metrics"

- edx_solutions_api_integration/imports/views.py
- setup.py
We fix it by just swapping the order of operations - try adding first, and if we get an integrity error, fallback to getting it.
> [MCKIN-8977] Fix a race condition in creating cohorts.

- edx_solutions_api_integration/courses/views.py
- setup.py
This optimizes `CourseMetricsLeaders.get` by gathering leaders with a `ThreadPool`.
The processing time for this view went down from around 250ms to 50ms on my local environment.
- Prepare course with some social engagement/progress/proficiency stats (one of them is sufficient in this case, because this PR does not modify the logic).
- Prepare user's token
```bash
curl -X GET \
http://{LMS}/api/server/courses/{course_id}/metrics/leaders/ \
-H 'Authorization: Bearer {token}' \
-H 'X-Edx-Api-Key: edx_api_key' \
-H 'cache-control: no-cache' \
-o /dev/null \
-sw 'Total: %{time_total}s\n'
```
- Stay with `api-integration:master`, make the request multiple times and get average time from it.
- Checkout to this branch and repeat making the request and getting average time.
- You can also check …
> [MCKIN-8891] Optimize CourseMetricsLeaders

- edx_solutions_api_integration/courses/views.py
- setup.py
The API was making at least 4 DB calls to get data from the same User table, and then doing for loops over all that data up to 3 times to populate a list and filter things down.
This kills the for loop and makes 1 DB call.
Test instructions:
1. Start up the LMS.
1. Do this before and after going onto this branch, and compare the times and outputs. (Remove the `-o` flag and its value to see output).
```bash
curl -X GET \
http://lms.mcka.local/api/server/courses/course-v1:edX%2BDemoX%2BDemo_Course/roles/ \
-H 'Authorization: Bearer <token>' \
-H 'X-Edx-Api-Key: edx_api_key' \
-H 'cache-control: no-cache' \
-o /dev/null \
-sw 'Total: %{time_total}s\n'
```
1. Make sure the resulting list is the same (though order may differ), but that the time taken is less. You can also just use silk.
1. …
> [MCKIN-8963] Optimize CoursesRolesList.get

- edx_solutions_api_integration/imports/views.py
- setup.py
See the ticket and most recent comments for why we catch this now too. `add_cohort` throws it.
> [MCKIN-8977] Also catch a ValueError.

- edx_solutions_api_integration/courses/views.py
- setup.py
This just adds the option to order by different fields than the ID by the client. The default ordering was the ID so we keep it that way. See private repo for test instructions.
> [MCKIN-8978] Add the ability to order users for this API.

- edx_solutions_api_integration/users/tests.py
- edx_solutions_api_integration/users/views.py
- setup.py
The DELETE method only accepts either 'username' or 'ids'
parameters. The User objects matching the filter are deleted from the
database.
Example usages:
```
DELETE /api/users?ids=23
DELETE /api/users?ids=23,24,25
DELETE /api/users?username=edx
```
> MCKIN-8911 & BB-707 Add DELETE method for users api

- edx_solutions_api_integration/users/tests.py
- edx_solutions_api_integration/users/views.py
- setup.py
**Story:**
The user is locked out after entering the incorrect password 3 times and was not able to get in for 30 minutes even when they try to reset their password, which is misleading.
**Ticket Criteria:**
If User is locked out and reset the password, the locked out is removed and he can log in with the new password.
> Remove the lockout after I reset my password

- edx_solutions_api_integration/courses/views.py
- setup.py
Allow filtering CoursesUsersList endpoint by users so we can make efficient queries for the manager dashboard.
**JIRA tickets**: MCKIN-9071
**Discussions**: See ticket.
**Dependencies**: None
**Screenshots**:
**Sandbox URL**: TBD - sandbox is being provisioned.
**Merge deadline**: ?
1. Send a query to the CoursesUsersList endpoint providing a ?users=1,2,3 query param (where 1,2,3 are user ids that would otherwise be returned in the response).
**Author notes and concerns**:
This has the same potential to overrun the max URL size that we encountered in the competion-aggregator api, but we won't see this anytime soon in production, because no manager has more than 72 reports.  Currently, apros is restricting itself to requesting at most 100 user ids, so this won't …
> MCKIN-9071: Fix manager reports view.

- edx_solutions_api_integration/courses/urls.py
- edx_solutions_api_integration/courses/utils.py
- edx_solutions_api_integration/courses/views.py
- setup.py
Currently to get course engagement summary call two APIs and performs calculations on response of those APIs which very slow for a large cohort set, This PR introduces a new API which returns calculated stats. Currently Engagement Summary took 43.24 seconds to load for a course with about 50k cohort, New API is taking 835.75 ms for the same course.
Testing Instructions:
Install this PR branch for api-integration in LMS.
Call `/api/server/courses/{course_id}/engagement-summary` with Bearer token.
> MCKIN-9466: adds course engagement summary api

- edx_solutions_api_integration/users/views.py
- setup.py
Description
=========
The discussion API fails when required to retire an user that doesn't exist on discussions yet. This can cause problems when deleting an user that have not accessed the discussion and this PR ignores this specific error when deleting an user.
Testing
--------
1. Create an user and immediately remove it, to make sure no discussion user is created.
2. The deletion proceeds without errors.
> [MCKIN-8918] Fix deleting user without discussion posts

- edx_solutions_api_integration/imports/views.py
- setup.py
Fixing import participants from CSV and Enroll existing participants issue which was throwing HTTP INTERNAL SERVER ERROR (500) for Internal Admin.
> MCKIN-9798-Import/Enroll participants from CSV Fix

- edx_solutions_api_integration/users/tests.py
- edx_solutions_api_integration/users/views.py
- setup.py
https://github.com/edx-solutions/edx-platform/pull/1359 introduces a new api method for deleting users and other related records.
This PR updates the DELETE api introduced from #188 to use the new method from https://github.com/edx-solutions/edx-platform/pull/1359. 
Example usage is unchanged from #188 
```
DELETE /api/users?ids=23
DELETE /api/users?ids=23,24,25
DELETE /api/users?username=edx
```
> BB-742 Delete users using the new delete_user method

- edx_solutions_api_integration/users/tests.py
- setup.py
This removes the debug trace statements added accidentally in https://github.com/edx-solutions/api-integration/pull/197
@viadanna, do I have to bump the version for this change as well?
> Remove debug trace statements

- edx_solutions_api_integration/courses/tests.py
- edx_solutions_api_integration/courses/views.py
- edx_solutions_api_integration/test_utils.py
- edx_solutions_api_integration/urls.py
- edx_solutions_api_integration/users/views.py
- setup.py
The data CourseAggregatedMetaData was storing is now provided by the completion aggregator, code using it and  signals keeping it in sync can be removed.
> [MCKIN-7759] Remove usage of CourseAggregatedMetaData since it is no longer in use.

- edx_solutions_api_integration/management/commands/add_test_poll_responses.py
- setup.py
This PR adds a management command that creates dummy responses for polls and surveys for users enrolled in a course.
1. On your solutions devstack, clone and install this branch.
2. Create a course with some polls and surveys (or import this one: [2019_T1.wJUdry.tar.gz](https://github.com/edx-solutions/api-integration/files/2983832/2019_T1.wJUdry.tar.gz)).
3. From `apros` [bulk import participants](http://apros.mcka.local/admin/participants) and add them to the course with the polls and surveys you just created. You can generate a CSV to bulk import users with:
```
with open('/tmp/participants.csv', 'w') as f:
for i in range(int(1e4)):
f.write(f"Bruce,Wayne,bruce{i}@wayne.com,1,TestX/TS101/2019_T1,participant\n")
```
4. Log in as a user and answer the polls.
5. Use the management command …
> MCKIN-10180: Add dummy poll response generator

- edx_solutions_api_integration/users/views.py
- setup.py
Profile image gets broken whenever we edit the username
The issue is fixed by copying the uploaded image files and saving them again for all four sizes according to the new username and then deleting the old images from storage.
The issue which we are facing on qa is fixed. Here is the link to the issue https://rpm.newrelic.com/accounts/631098/applications/4390895/traced_errors/fe236277-5c46-11e9-ada9-0242ac11000a_0_4365
> Fix profile image issue on editing username

- edx_solutions_api_integration/courses/tests.py
- edx_solutions_api_integration/courses/views.py
- edx_solutions_api_integration/users/views.py
- setup.py
This PR updates course overview and user courses API to return course overview image set rather than returning full-sized raw image, which can sometimes be huge in size and take a lot of time to load causing bad user experience.
Testing Notes:
This change requires course overview image sets enabled, to enable it go to [course overview images config page](http://lms.mcka.local/admin/course_overviews/courseoverviewimageconfig/) in django admin and add new config.
> MCKIN-9499: update course overview and user courses api to return image urls

- edx_solutions_api_integration/courses/views.py
- setup.py
This PR caches total users count so that if course data is served from the cache it also contains total users count
> MCKIN-11198: Total count of users is not appearing on cohort page

- edx_solutions_api_integration/tasks.py
- setup.py
Convert Ooyala ids in Adventure xblock to Brightcove Ids.
e.g; content_id in following tag  
`<ooyala-player content_id="VtZWc4ODE61SNu7RdCJTlDhHLJ23vl5d">`
will be converted to
`<ooyala-player content_id="6068614553001">`
> MCKIN-11499 - adventure xblock conversion

- edx_solutions_api_integration/tasks.py
- setup.py
Ooyala IDs can also contain hyphens `-`. Modified regex to support it.
> MCKIN-11606 - regex fix for ooyala ids

- edx_solutions_api_integration/tasks.py
- setup.py
Flush course cache so course blocks API could return updated data after migration script is run.
> MCKIN-12624 - clear course cache after running o2b migration script

- edx_solutions_api_integration/apps.py
In ironwood platform is moving all startup code to more standard locations using Django best practices. I have moved solutions_api configs to api-integrations and removed from lms/startup.py
> moving setup configs for solutions_api from lms/strartup.py to apps.py

- edx_solutions_api_integration/templates/bcove_ie_embed.html
- setup.py
Changing IE embed as IE now supports it after https://github.com/edx-solutions/xblock-image-explorer/pull/71 is merged.
> MCKIN-12728 - IE embed code update

- edx_solutions_api_integration/sessions/urls.py
- edx_solutions_api_integration/sessions/views.py
- setup.py
API to get an access token for assets access. 
- This assets token can be used to request locked LMS assets by passing them in request param
e.g; `/c4x/ToolsORG/Tools101/asset/Getting_started.pdf?auth_token={asset_token}`
- It is created by encrypting a valid user session id
- The encrypted token has time stamp attached with it so it also be used to implement temporary link of assets
> MCKIN-13351 - access token support for LMS assets

- edx_solutions_api_integration/sessions/views.py
`bytes` needs encoding argument:
```
edx.devstack-juniper.lms |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/rest_framework/views.py", line 492, in dispatch
edx.devstack-juniper.lms |     response = handler(request, *args, **kwargs)
edx.devstack-juniper.lms |   File "/edx/src/api-integration/edx_solutions_api_integration/sessions/views.py", line 273, in get
edx.devstack-juniper.lms |     response_data['assets_token'] = Fernet(bytes(settings.ASSETS_TOKEN_ENCRYPTION_KEY))\
edx.devstack-juniper.lms | TypeError: string argument without an encoding
edx.devstack-juniper.lms | [21/Dec/2020 11:25:28] "GET /api/server/sessions/ggylrh1l80r7x9yb1hf6k23lu588co2h/assets_token HTTP/1.0" 500 126108
```
> MCKIN-28615 - fix bytes conversion

- edx_solutions_api_integration/imports/views.py
CourseEnrollment does not update enrollment status when we face an integrity error on `CohortMembership.objects.create` during enrolling user to the same course multiple times. Used platform build-in function to avoid integrity.
Steps to reproduce:
1. Try to enroll user through the feature `Enroll existing participants`
2. unenroll this user from the course
3. Repeat it, the course will not be shown in the user's active courses.
> MCKIN-29700 existing user enrollments issue

- edx_solutions_api_integration/management/commands/add_test_poll_responses.py
- setup.py
Fixing errors in existing management command to add test polls data. Fixed types of arguments. Also added check that if argument `num-responses` is 0 than dummy response will be generated for each user as mentioned in the comments.
> MCKIN-30711 - Fixing errors in management command
